package com.github.biltudas1.dialsome;

import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.Notification;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.util.Log;
import androidx.core.app.NotificationCompat;
import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;
import java.util.Map;
import android.media.AudioAttributes;
import android.media.RingtoneManager;
import android.net.Uri;

public class MyFirebaseMessagingService extends FirebaseMessagingService {
    private static final String TAG = "DialSomeFCM";
    private static final int INCOMING_CALL_NOTIF_ID = 1001;

    // Native method to notify the C++ Backend that a message arrived
    public native void onCallMessageReceive(String roomId, String email, String roomName);
    public native void onCallMessageEnd(String email);
    private native void notifyNewToken(String token);

    /**
     * Called when a new token is generated.
     */
    @Override
    public void onNewToken(String token) {
        super.onNewToken(token);
        notifyNewToken(token);
        // In a real scenario, you'd send this to your /users/update-fcm endpoint
    }

    /**
     * Called when a message is received from the FastAPI backend.
     */
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);

        if (remoteMessage.getData().size() > 0) {
            Map<String, String> data = remoteMessage.getData();
            String type = data.get("type");
            if ("incoming_call".equals(type)) {
                String roomId = data.get("room_id"); // The UUIDv7/v4 generated by backend
                String callerEmail = data.get("caller_email");
                String callerName = data.get("caller_name");

                Log.d(TAG, "FCM Signal: " + type + " Room: " + roomId + " From: " + callerEmail + "(" + callerName + ")");
                wakeUpApp(callerEmail, roomId, callerName);
            } else if ("end_call".equals(type)) {
                NotificationManager nm = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
                nm.cancel(INCOMING_CALL_NOTIF_ID);

                String email = data.get("to");
                Log.d(TAG, "FCM Signal: " + type + " to: " + email);
                try {
                    onCallMessageEnd(email);
                } catch (UnsatisfiedLinkError e) {
                    Log.d(TAG, "Unable to end call, C++ is dead");
                }
            }
        }
    }

    private void wakeUpApp(String callerEmail, String roomId, String roomName) {
        NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        String channelId = "IncomingCalls";

        // Create Intent for the "Accept" action
        Intent acceptIntent = new Intent(this, CallActionReceiver.class);
        acceptIntent.setAction("ACCEPT_CALL");
        acceptIntent.putExtra("room_id", roomId);
        acceptIntent.putExtra("caller_email", callerEmail);
        acceptIntent.putExtra("caller_name", roomName);
        PendingIntent acceptPending = PendingIntent.getBroadcast(this, 10, acceptIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);

        // Create Intent for the "Reject" action
        Intent rejectIntent = new Intent(this, CallActionReceiver.class);
        rejectIntent.setAction("REJECT_CALL");
        rejectIntent.putExtra("caller_email", callerEmail);
        PendingIntent rejectPending = PendingIntent.getBroadcast(this, 11, rejectIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);

        Uri ringtoneUri = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_RINGTONE);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channel = new NotificationChannel(channelId, "Incoming Calls", NotificationManager.IMPORTANCE_HIGH);
            AudioAttributes audioAttributes = new AudioAttributes.Builder()
                    .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                    .setUsage(AudioAttributes.USAGE_NOTIFICATION_RINGTONE)
                    .build();
            channel.setSound(ringtoneUri, audioAttributes);
            notificationManager.createNotificationChannel(channel);
        }

        NotificationCompat.Builder builder = new NotificationCompat.Builder(this, channelId)
                .setSmallIcon(android.R.drawable.ic_menu_call) // Optional: replace with R.drawable.icon
                .setContentTitle("Incoming Call")
                .setContentText("Call from " + roomName)
                .setPriority(NotificationCompat.PRIORITY_HIGH)
                .setCategory(NotificationCompat.CATEGORY_CALL)
                // Set the pending intents
                .setFullScreenIntent(acceptPending, true) 
                .setContentIntent(acceptPending) // Tapping the notification body accepts the call
                .setSound(ringtoneUri)
                .setOngoing(true)
                .setAutoCancel(true)
                // Add the actual UI buttons to the notification
                .addAction(android.R.drawable.ic_menu_call, "Accept", acceptPending)
                .addAction(android.R.drawable.ic_menu_close_clear_cancel, "Reject", rejectPending);

        Notification notification = builder.build();
        notification.flags |= Notification.FLAG_INSISTENT; // Keeps the ringtone looping
        notificationManager.notify(INCOMING_CALL_NOTIF_ID, notification);
    }
}
