package com.github.biltudas1.dialsome;

import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.Notification;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.util.Log;
import androidx.core.app.NotificationCompat;
import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;
import java.util.Map;
import android.media.AudioAttributes;
import android.media.RingtoneManager;
import android.net.Uri;

public class MyFirebaseMessagingService extends FirebaseMessagingService {
    private static final String TAG = "DialSomeFCM";

    // Native method to notify the C++ Backend that a message arrived
    public native void onCallMessageReceive(String roomId, String email, String roomName);
    public native void onCallMessageEnd(String email);
    private native void notifyNewToken(String token);

    /**
     * Called when a new token is generated.
     */
    @Override
    public void onNewToken(String token) {
        super.onNewToken(token);
        notifyNewToken(token);
        // In a real scenario, you'd send this to your /users/update-fcm endpoint
    }

    /**
     * Called when a message is received from the FastAPI backend.
     */
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);

        if (remoteMessage.getData().size() > 0) {
            Map<String, String> data = remoteMessage.getData();
            String type = data.get("type");
            if ("incoming_call".equals(type)) {
                String roomId = data.get("room_id"); // The UUIDv7/v4 generated by backend
                String callerEmail = data.get("caller_email");
                String callerName = data.get("caller_name");

                Log.d(TAG, "FCM Signal: " + type + " Room: " + roomId + " From: " + callerEmail + "(" + callerName + ")");

                try {
                    onCallMessageReceive(roomId, callerEmail, callerName);
                } catch (UnsatisfiedLinkError e) {
                    Log.d(TAG, "C++ is dead. Waking up the app via Notification...");
                    wakeUpApp(callerEmail, roomId, callerName);
                }
            } else if ("end_call".equals(type)) {
                String email = data.get("to");

                Log.d(TAG, "FCM Signal: " + type + " to: " + email);

                try {
                    onCallMessageEnd(email);
                } catch (UnsatisfiedLinkError e) {
                    Log.d(TAG, "Unable to end call, C++ id dead");
                }
            }
        }
    }

    private void wakeUpApp(String callerEmail, String roomId, String roomName) {
        Intent intent = new Intent(this, org.qtproject.qt.android.bindings.QtActivity.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP);
        intent.putExtra("incoming_room_id", roomId);
        intent.putExtra("incoming_caller", callerEmail);

        PendingIntent pendingIntent = PendingIntent.getActivity(this, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);

        String channelId = "IncomingCalls";
        NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);

        // Retrieve the default ringtone URI
        Uri ringtoneUri = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_RINGTONE);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channel = new NotificationChannel(channelId, "Incoming Calls", NotificationManager.IMPORTANCE_HIGH);
            
            // Set the sound on the NotificationChannel
            AudioAttributes audioAttributes = new AudioAttributes.Builder()
                    .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                    .setUsage(AudioAttributes.USAGE_NOTIFICATION_RINGTONE)
                    .build();
            channel.setSound(ringtoneUri, audioAttributes);
            
            notificationManager.createNotificationChannel(channel);
        }

        NotificationCompat.Builder builder = new NotificationCompat.Builder(this, channelId)
                // YOU MUST HAVE AN ICON HERE, e.g., R.drawable.icon
                .setSmallIcon(android.R.drawable.ic_menu_call) 
                .setContentTitle("Incoming Call")
                .setContentText("Call from " + roomName)
                .setPriority(NotificationCompat.PRIORITY_HIGH)
                .setCategory(NotificationCompat.CATEGORY_CALL)
                .setFullScreenIntent(pendingIntent, true) // THIS WAKES UP THE SCREEN
                .setSound(ringtoneUri) // Set the sound on the Builder for older Android versions
                .setOngoing(true)
                .setAutoCancel(true);

        Notification notification = builder.build();
        notification.flags |= Notification.FLAG_INSISTENT;
        notificationManager.notify(1001, notification);
    }
}